### ISSUE TITLE
List out the cloud technology that we would like to explore

### ISSUE THREAD

**Issue by bedatse** [palo-it-hk/dev-experience#1]

**Comment by aliu-paloit** [comment]
- Azure
- React with hooks in TypeScript
- Redux
- NodeJS service in plain Docker also in TypeScript

**Comment by aliu-paloit** [comment]
- Typical VPN service offered by cloud
- Spinning up a lightweight sandbox environment for Front-end or Back-end development to minimize pulling and refreshing
- Simple CI/CD in a sandbox environment
- lightweight database querying interface
- Linux ecosystem in cloud

**Comment by bedatse** [comment]
I have created #8 #9 #10 #11 #12 #13 #14 #15 #16 to cover these first batch of topics
